# create&release workflow for Magisk Module Git v1.0.0 by Mehrab Mahmud Udoy 

name: create&release  
on: 
  push:
    branches:
      - main 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
            path: 'update.json'
            prop_path: 'version'
      - name: Creating module zip
        run:  |
          sudo zip -r ${{ github.event.repository.name }}.zip *  
      - name: Github Release create, update, and upload assets
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.version.outputs.prop}}
          name: ${{steps.version.outputs.prop}}
          body: Please check [changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for changes
          files: ${{ github.event.repository.name }}.zip
          gzip: false
          draft: false
          prerelease: false
          allow_override: true
      - name: Cleanup module zip
        run:  |
          rm ${{ github.event.repository.name }}.zip
